Update package.json
Command: `npm run test:debug` raise error (because trying loading shell script but not js script):
--------------------------
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
------------

My fix correct it